Docker is work

diff --git a/compose/django/entrypoint b/compose/django/entrypoint
--- a/compose/django/entrypoint
+++ b/compose/django/entrypoint
@@ -1,18 +1,36 @@
-#!/bin/sh
+#!/bin/bash
 
-if [ "$DATABASE" = "postgres" ]
-then
-    echo "Waiting for postgres..."
+# if any of the commands in your code fails for any reason, the entire script fails
+set -o errexit
+# fail exit if one of your pipe command fails
+set -o pipefail
+# exits if any of your variables is not set
+set -o nounset
 
-    while ! nc -z $POSTGRES_HOST $POSTGRES_PORT; do
-      sleep 0.1
-    done
+postgres_ready() {
+python << END
+import sys
 
-    echo "PostgreSQL started"
-fi
+import psycopg2
 
-python manage.py makemigrations
-python manage.py migrate
-python manage.py collectstatic --noinput
-#python manage.py runserver 0.0.0.0:8000
-gunicorn core.wsgi:application --bind 0.0.0.0:8000
+try:
+    psycopg2.connect(
+        dbname="${SQL_DATABASE}",
+        user="${SQL_USER}",
+        password="${SQL_PASSWORD}",
+        host="${SQL_HOST}",
+        port="${SQL_PORT}",
+    )
+except psycopg2.OperationalError:
+    sys.exit(-1)
+sys.exit(0)
+
+END
+}
+until postgres_ready; do
+  >&2 echo 'Waiting for PostgreSQL to become available...'
+  sleep 1
+done
+>&2 echo 'PostgreSQL is available'
+
+exec "$@"
